save_path: '/results'
rask_name: 'HyRankD_to_L' #Houston13_to_18 | PaviaU_to_C | S_to_H | HyRankD_to_L | HyRankL_to_D
gpu: 2
patch_size: 13
batch_size: 256
lr_scheduler: 'cosine' #cosine | Exp |Step
num_epoch: 200
seed: 233


depth: 6
embed_dim: 256
act_num: 1
patch_mixup_keep: 0.5

use_middle_cls_token: True
if_random_cls_token_position: False
if_random_token_rank: False
flip_augmentation: True
radiation_augmentation: True
mixture_augmentation: False

rms_norm: True
residual_in_fp32: True
fused_add_norm: True
final_pool_type: 'mean'
if_abs_pos_embed: True
bimamba_type: "v2"
if_cls_token: True
if_devide_out: True
